#!/bin/bash
# Full offline bring-up for the 30-second recorded-video test (realroom30).
# Localization = wheel odometry via static map->odom TF (phone disconnected).
# Environment = the captured realroom30 map/world only. No AMCL.
# All kill patterns in-file (pkill trap safety).
pkill -f 'simulation.launch.py' 2>/dev/null
pkill -f 'localization.launch.py' 2>/dev/null
pkill -f 'navigation.launch.py' 2>/dev/null
pkill -f 'gz-sim-main' 2>/dev/null
pkill -f 'parameter_bridge' 2>/dev/null
pkill -f 'ros_gz_create' 2>/dev/null
pkill -f 'amcl' 2>/dev/null
pkill -f 'map_server' 2>/dev/null
pkill -f 'planner_server' 2>/dev/null
pkill -f 'controller_server' 2>/dev/null
pkill -f 'behavior_server' 2>/dev/null
pkill -f 'smoother_server' 2>/dev/null
pkill -f 'lifecycle_manager' 2>/dev/null
pkill -f 'depth_to_scan' 2>/dev/null
pkill -f 'depth_bridge_node' 2>/dev/null
pkill -f 'depth_pipeline_node' 2>/dev/null
pkill -f 'pointcloud_costmap_layer' 2>/dev/null
pkill -f 'static_transform_publisher' 2>/dev/null
pkill -f 'rviz2' 2>/dev/null
sleep 5

# GENERIC MODE: every dataset-specific value comes from the environment
# (nav_targets.env generated by scripts/fyp30_run_pipeline.sh for ANY input
# video). Explicit env still wins; nothing is hardcoded to one dataset.
if [ -n "$FYP_DATASET_ENV" ] && [ -r "$FYP_DATASET_ENV" ]; then
    . "$FYP_DATASET_ENV"
fi
# Every dataset-specific value MUST come from the environment (nav_targets.env
# written by fyp30_run_pipeline.sh). No dataset defaults live in this script.
: "${FYP_MAP:?FAIL: FYP_MAP unset - run scripts/fyp30_run_pipeline.sh <video>, then: set -a; source <dataset>/nav_targets.env; set +a}"
: "${FYP_WORLD:?FAIL: FYP_WORLD unset - run scripts/fyp30_run_pipeline.sh <video> first}"
: "${FYP_WORLD_NAME:?FAIL: FYP_WORLD_NAME unset - run scripts/fyp30_run_pipeline.sh <video> first}"
: "${SPAWN_X:?FAIL: SPAWN_X unset (auto-selected from the reconstruction)}"
: "${SPAWN_Y:?FAIL: SPAWN_Y unset (auto-selected from the reconstruction)}"
FYP_NO_RVIZ=${FYP_NO_RVIZ:-0}
[ -r "$FYP_MAP" ] || { echo "FAIL: map not found: $FYP_MAP"; exit 1; }
[ -r "$FYP_WORLD" ] || { echo "FAIL: world not found: $FYP_WORLD"; exit 1; }

echo "== killed; starting backend (video stream locked: offline) =="
FYP_VIDEO_STREAM_LOCK=1 setsid nohup bash "$HOME/FYP/run_backend.sh" > /tmp/fyp_backend.log 2>&1 &
sleep 15

echo "== sim (world $FYP_WORLD, spawn $SPAWN_X,$SPAWN_Y) =="
setsid env FYP_WORLD=$FYP_WORLD \
    FYP_SPAWN_X=$SPAWN_X FYP_SPAWN_Y=$SPAWN_Y \
    "$HOME/FYP/scripts/fyp_phase.sh" indoor_nav_gazebo simulation.launch.py \
    > /tmp/fyp_sim30.log 2>&1 &
sleep 30

echo "== static map->odom TF =="
# With OdometryPublisher (true-pose odom) odom==world, so the map->odom TF
# must be identity; TF_X/TF_Y override keeps the old +SPAWN convention
# available for wheel-integration odom.
setsid nohup /opt/ros/lyrical/lib/tf2_ros/static_transform_publisher \
    --x ${TF_X:-0} --y ${TF_Y:-0} --z 0 --roll 0 --pitch 0 --yaw 0 \
    --frame-id map --child-frame-id odom > /tmp/fyp_static_tf30.log 2>&1 &
sleep 2
# OdometryPublisher (new drive) emits odom -> fyp_robot/base_footprint, while
# nav2 + the depth pipeline anchor on bare base_link. Identity static joins
# them so map->odom->fyp_robot/base_footprint->base_link is one tree.
setsid nohup /opt/ros/lyrical/lib/tf2_ros/static_transform_publisher \
    --x 0 --y 0 --z 0 --roll 0 --pitch 0 --yaw 0 \
    --frame-id fyp_robot/base_footprint --child-frame-id base_link \
    > /tmp/fyp_footprint_tf.log 2>&1 &
sleep 2

echo "== map server (BEFORE nav2 so costmaps init with the map) =="
source /opt/ros/lyrical/setup.bash
source "$HOME/FYP/ros2_ws/install/setup.bash"
export ROS_DOMAIN_ID=0
setsid nohup ros2 run nav2_map_server map_server \
    --ros-args -r __node:=map_server \
    -p yaml_filename:=$FYP_MAP \
    -p use_sim_time:=true -p frame_id:=map \
    > /tmp/fyp_mapserver30.log 2>&1 &
sleep 3
for st in configure activate; do
  for i in 1 2 3 4 5 6; do
    CUR=$(timeout 6 ros2 lifecycle get /map_server 2>/dev/null)
    case "$CUR" in
      active*) break 2 ;;
      inactive*) [ "$st" = "activate" ] && timeout 8 ros2 lifecycle set /map_server activate >/dev/null 2>&1; sleep 1 ;;
      *) [ "$st" = "configure" ] && timeout 8 ros2 lifecycle set /map_server configure >/dev/null 2>&1; sleep 1 ;;
    esac
  done
done
echo "map_server: $(timeout 10 ros2 lifecycle get /map_server 2>/dev/null)"

echo "== perception pipeline (offline stale republish + grid bridge) =="
setsid nohup ros2 run smartphone_depth_bridge depth_bridge_node \
    --ros-args -p backend_url:=http://127.0.0.1:8000/latest-depth-image \
    -p depth_topic:=/smartphone/depth -p depth_frame_id:=camera_depth_frame \
    -p use_sim_time:=true -p republish_stale:=true \
    > /tmp/fyp_bridge30.log 2>&1 &
sleep 2
setsid nohup ros2 run indoor_nav_costmap depth_pipeline_node \
    --ros-args -p depth_topic:=/smartphone/depth \
    -p pointcloud_topic:=/camera/depth/points \
    -p grid_topic:=/depth_occupancy_grid \
    -p frame_id:=camera_depth_frame -p use_sim_time:=true \
    > /tmp/fyp_pipeline30.log 2>&1 &
sleep 2
setsid nohup ros2 run indoor_nav_costmap pointcloud_costmap_layer \
    --ros-args -p grid_topic:=/depth_occupancy_grid \
    -p pointcloud_topic:=/camera/depth/points \
    -p map_topic:=/smartphone_map -p use_sim_time:=true \
    > /tmp/fyp_gridbridge30.log 2>&1 &
sleep 6

echo "== nav2 on $FYP_MAP =="
setsid env FYP_MAP=$FYP_MAP \
    "$HOME/FYP/scripts/fyp_phase.sh" indoor_nav_costmap navigation.launch.py \
    > /tmp/fyp_nav30_launch.log 2>&1 &
sleep 35

# wait for each managed node to reach active; nudge transitions lost under load
for node in controller_server planner_server behavior_server bt_navigator; do
  for try in 1 2 3 4 5 6; do
    ST=$(timeout 20 ros2 lifecycle get /$node 2>/dev/null)
    case "$ST" in
      active*) echo "$node: $ST"; break ;;
      inactive*)
        timeout 30 ros2 lifecycle set /$node activate 2>/dev/null; sleep 2 ;;
      *)
        timeout 30 ros2 lifecycle set /$node configure 2>/dev/null
        sleep 2
        timeout 30 ros2 lifecycle set /$node activate 2>/dev/null
        sleep 2 ;;
    esac
  done
done
echo "== final nav states =="
for node in controller_server planner_server behavior_server bt_navigator; do
  echo "$node: $(timeout 20 ros2 lifecycle get /$node 2>/dev/null)"
done

echo "== GUIs =="
setsid bash -c 'export DISPLAY=:0; exec gz sim -g -v 2' > /tmp/fyp_gzgui30.log 2>&1 &
sleep 6
if [ "$FYP_NO_RVIZ" != "1" ]; then
  setsid bash -c 'source /opt/ros/lyrical/setup.bash; source '$HOME'/FYP/ros2_ws/install/setup.bash; export DISPLAY=:0; exec rviz2 -d '$HOME'/FYP/rviz_live_view.rviz' > /tmp/fyp_rviz30.log 2>&1 &
  sleep 3
fi

# --- AUTO-UNPAUSE + FLOW VERIFICATION -------------------------------------
# The sim should start running (gz sim -r), but some sessions come up paused
# (clock frozen at 0 => no /odom, no gz /tf). Force-unpause via the world
# control service, then verify clock + odom + gz-side /tf actually flow.
export GZ_IP=127.0.0.1
WNAME=$(grep -o '<world name="[^"]*"' "$FYP_WORLD" | head -1 | sed 's/.*name="//;s/"//')
echo "== unpause world '$WNAME' (if paused) =="
setsid nohup gz service -s /world/$WNAME/control \
    --reqtype gz.msgs.WorldControl --reptype gz.msgs.Boolean --timeout 5000 \
    --req 'pause: false' > /tmp/fyp_unpause30.log 2>&1 &
sleep 3
CLK=$(timeout 8 ros2 topic echo /clock --once 2>/dev/null | grep -m1 sec)
echo "clock: ${CLK:-NONE}"
ODOM=$(timeout 8 ros2 topic echo /odom --once --field pose.pose.position 2>/dev/null | tr '\n' ' ')
echo "odom: ${ODOM:-NONE}"
GZTF=$(timeout 6 gz topic -i -t /tf 2>/dev/null | grep -m1 publisher)
echo "gz /tf: ${GZTF:-NO PUBLISHER}"
echo "DONE bringup (spawn $SPAWN_X,$SPAWN_Y)"
